using System.Text;
using Microsoft.CodeAnalysis;

namespace Cadmus.Domain;

[Generator]
public class SystemsRegistryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            {
                ctx.AddSource(
                    "SystemsRegistry.init.g.cs", 
                    """
                    // <auto-generated/>
                    using System;
                    using System.Collections.Generic;
                    using Cadmus.Domain.Contracts;

                    namespace Cadmus.Domain;

                    public static partial class SystemsRegistry
                    {
                        public static readonly Dictionary<Type, ISystem> Instances = new();
                    }
                    """
                );
            }
        );

        var compilationProvider = context.CompilationProvider.Select(
            static (compilation, _) => compilation);

        context.RegisterSourceOutput(compilationProvider, Execute);
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        var interfaceSymbol = compilation.GetTypeByMetadataName("Cadmus.Domain.Contracts.ISystem");
        if (interfaceSymbol is null) return;

        var implementations = compilation.SourceModule.GlobalNamespace
            .GetNamespaceMembers()
            .SelectMany(ns => ns.GetTypeMembers())
            .Where(type => type.AllInterfaces.Contains(interfaceSymbol))
            .ToList();

        if (implementations.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace Cadmus.Domain;");
        sb.AppendLine();
        sb.AppendLine("public static partial class SystemsRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    static SystemsRegistry()");
        sb.AppendLine("    {");
        
        foreach (var impl in implementations)
        {
            var typeName = impl.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", "");
            sb.AppendLine($"        Instances.Add(typeof({typeName}), new {typeName}());");
        }
        
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("SystemsRegistry.impl.g.cs", sb.ToString());
    }
}
